# -*- coding: utf-8 -*-
{
    'name': "Hospital Module",
    'summary': "Hospital management",
    'description': """Hospital management.""",
    'category': 'Extra Tools',
    'version': '1.0',
    'depends': ['base', 'mail', 'sale', 'board', 'stock', 'purchase', 'report_xlsx', 'website', 'stock_barcode', 'purchase'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/template_js.xml',
        'data/sequence.xml',
        'reports/report.xml',
        'data/mail_template.xml',
        'data/hospital.patient.csv',
        'data/hospital_patient_data.xml',
        'data/cron.xml',
        'views/patient.xml',
        'views/appointment_view.xml',
        'views/doctor_view.xml',
        'views/lab.xml',
        'views/sale_order.xml',
        'views/dashboard.xml',
        'views/purchase_order_view.xml',
        'views/template.xml',
        'views/settings.xml',
        'views/book_category_view.xml',
        'wizards/create_appointment.xml',
        'reports/patient_card.xml',
        'reports/appointment_card.xml',
        'reports/sale_report_inherit.xml',
        'reports/delivery_picking.xml',
        'reports/delivery_slip.xml',
        'reports/invoice_inherit.xml',
        'reports/purchase_inherit.xml',
    ],
}
# Part of Odoo. See LICENSE file for full copyright and licensing details.
